apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls-front
spec:
  secretName: app-tls-secret-front
  commonName: workflow.rifnology.com
  dnsNames:
  - workflow.rifnology.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
