apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.company_name }}-workflow-frontend-svc
spec:
  selector:
    app: {{ .Values.company_name }}-workflow-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80

